const express = require('express');
const router = express.Router();
const Income = require('../models/Income');

// GET: Get incomes, optionally filtered by year and month
router.get('/', async (req, res) => {
  try {
    const { year, month } = req.query;
    let filter = {};

    const now = new Date();
    const currentYear = now.getUTCFullYear();
    const currentMonth = now.getUTCMonth(); // 0-indexed

    // Auto-copy logic runs only for current month
    const startOfCurrentMonth = new Date(Date.UTC(currentYear, currentMonth, 1));
    const endOfCurrentMonth = new Date(Date.UTC(currentYear, currentMonth + 1, 1));

    // Check if any income exists in the current month
    const incomeExists = await Income.exists({
      date: { $gte: startOfCurrentMonth, $lt: endOfCurrentMonth }
    });

    if (!incomeExists) {
      // Get the most recent income before this month
      const latestIncome = await Income.findOne({ date: { $lt: startOfCurrentMonth } }).sort({ date: -1 });
      if (latestIncome) {
        const copiedIncome = new Income({
          amount: latestIncome.amount,
          source: latestIncome.source,
          date: startOfCurrentMonth,
          autoGenerated: true
        });
        await copiedIncome.save();
      }
    }

    // Apply year and month filter if present
    if (year) {
      const y = parseInt(year);
      if (!isNaN(y)) {
        if (month !== undefined && month !== '') {
          const m = parseInt(month);
          if (!isNaN(m)) {
            filter.date = {
              $gte: new Date(Date.UTC(y, m, 1)),
              $lt: new Date(Date.UTC(y, m + 1, 1))
            };
          } else {
            filter.date = {
              $gte: new Date(Date.UTC(y, 0, 1)),
              $lt: new Date(Date.UTC(y + 1, 0, 1))
            };
          }
        } else {
          filter.date = {
            $gte: new Date(Date.UTC(y, 0, 1)),
            $lt: new Date(Date.UTC(y + 1, 0, 1))
          };
        }
      }
    }

    const incomes = await Income.find(filter).sort({ date: 1 });
    res.json(incomes);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// POST: Add a new income
router.post('/', async (req, res) => {
  const { amount, source, date } = req.body;
  try {
    const newIncome = new Income({ amount, source, date });
    await newIncome.save();
    res.status(201).json(newIncome);
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
});

// DELETE: Delete an income by ID
router.delete('/:id', async (req, res) => {
  try {
    const income = await Income.findByIdAndDelete(req.params.id);
    if (!income) return res.status(404).json({ message: 'Income not found' });
    res.json({ message: 'Income deleted' });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;
