const express = require('express');
const multer = require('multer');
const axios = require('axios');
const router = express.Router();

// Multer setup for image uploads
const storage = multer.memoryStorage();
const upload = multer({ storage: storage });

// Google Gemini API configuration for Gemini 1.5 Flash
const GEMINI_API_KEY = process.env.GEMINI_API_KEY || 'GEMINI_API'; // Use environment variable or provided API key
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent'; // Use Gemini 1.5 Flash model

// POST /transactions/upload/upload-image
router.post('/upload-image', upload.single('image'), async (req, res) => {
  if (!req.file) {
    return res.status(400).json({ message: 'No image file provided.' });
  }

  if (!GEMINI_API_KEY || GEMINI_API_KEY === 'YOUR_GEMINI_API_KEY') { // Updated check
    console.error('Gemini API key is not configured.');
    return res.status(500).json({ message: 'AI service is not configured on the server.' });
  }

  try {
    // Convert image buffer to base64
    const imageBase64 = req.file.buffer.toString('base64');

    // Prepare the prompt and image data for the Gemini model
    const requestPayload = {
      contents: [
        {
          parts: [
            { text: 'Analyze the following receipt image and extract the total amount, category (e.g., groceries, fuel, food, shopping), date, payment type (e.g., cash, credit card, debit card), and a brief description of the transaction. Return the data in a clean JSON format like this:\n{\n  "amount": 123.45,\n  "category": "Groceries",\n  "date": "YYYY-MM-DD",\n  "paymentType": "Credit Card",\n  "description": "Brief description of items purchased"\n}' }, // Updated text prompt part to include payment type and description
            {
              inline_data: { // Image data part
                mime_type: req.file.mimetype,
                data: imageBase64
              }
            }
          ]
        }
      ]
    };

    // Call the Google Gemini Inference API
    const geminiResponse = await axios.post(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, requestPayload, // Send payload
      {
        headers: {
          'Content-Type': 'application/json',
        },
      }
    );

    // Extract the generated text from the response
    // Gemini response structure: response.data.candidates[0].content.parts[0].text
    const generatedText = geminiResponse.data?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
        console.error('No text generated by Gemini:', geminiResponse.data);
        throw new Error('AI service did not generate text.');
    }

    // Clean the response to extract only the JSON part
    // Assuming Gemini might also wrap JSON in code blocks
    const jsonMatch = generatedText.match(/```json\n([\s\S]*?)\n```/);
    
    if (!jsonMatch || !jsonMatch[1]) {
        console.error('Could not find JSON in Gemini response:', generatedText);
        // Fallback: try parsing the whole text if no code block is found
        try {
            const extractedData = JSON.parse(generatedText);
             res.json(extractedData);
             return;
        } catch (parseError) {
             console.error('Could not parse generated text as JSON:', parseError);
             throw new Error('Invalid response format from AI service.');
        }
    }

    const jsonString = jsonMatch[1];
    const extractedData = JSON.parse(jsonString);

    // Return the extracted data to the frontend
    res.json(extractedData);

  } catch (error) {
    console.error('Error processing image with Gemini API:', error.response ? error.response.data : error.message);
    res.status(500).json({ message: 'Failed to extract transaction from image using AI.' });
  }
});

module.exports = router;
